version: '3.8'

services:
  # Node.js 应用服务
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=3000
      - ENCRYPTION_KEY=f1e2d3c4b5a6978899aabbccddeeff00112233445566778899aabbccddeeff00
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  # MongoDB 服务
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_3y6JyM
      - MONGO_INITDB_ROOT_PASSWORD=mongo_iNySJ5
      - MONGO_INITDB_DATABASE=license-manager
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: 