name: Build Mac ARM Executable

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build MacOS ARM executable
      run: |
        pyinstaller CursorKeepAlive.spec
        
    - name: Copy and rename env file
      run: |
        cp .env.example dist/.env
        
    - name: Upload MacOS ARM artifact
      uses: actions/upload-artifact@v4
      with:
        name: CursorPro-MacOS-ARM64
        path: |
          dist/CursorPro
          dist/.env

  create-release:
    needs: [build-macos-arm64]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create release archives
        run: |
          cd artifacts
          zip -r CursorPro-MacOS-ARM64.zip CursorPro-MacOS-ARM64/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/CursorPro-MacOS-ARM64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 